/*-----------------------------------------------------------------------------------------------------
	FILE: CREATE_SEQUENCE.SQL
	DESCRIPTION: THIS SCRIPT CONTAIN SEQUENCE
	AUTHOR: SELVA
	DATE CREATED: 08/02/2021
*/-----------------------------------------------------------------------------------------------------

CREATE SEQUENCE ADDRESS_SEQ MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE ADMIN_SEQ MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE ASSIGNED_ROOM_SEQ MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE ASSIST_PATIENT_SEQ MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE ATTEND_PATIENT_SEQ MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE DOCTOR_SEQ MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 306 NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE GOVERNS_ROOM_SEQ MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE LOG_PATIENT_SEQ MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE NURSE_SEQ MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 406 NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE PATIENT_SEQ MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 108 NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE RECEPTIONIST_SEQ MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 506 NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE ROOM_SEQ MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 120 NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE USER_TYPE_SEQ MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

CREATE SEQUENCE LOGIN_INFO_SEQ MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
