/*-----------------------------------------------------------------------------------------------------
	FILE: CREATE_FUNCTIONS.SQL
	DESCRIPTION: THIS SCRIPT CONTAIN FUNCTIONS
	AUTHOR: SELVA
	DATE CREATED: 10/02/2021
*/-----------------------------------------------------------------------------------------------------

create or replace FUNCTION FIND_DOCTOR_ID(doctorid IN DOCTOR.D_ID%TYPE)
RETURN BOOLEAN AS 
FLAG NUMBER(5):=0;
CURSOR DOC_REC IS
SELECT D_ID FROM ATTEND_PATIENT;
BEGIN
  FOR I IN DOC_REC LOOP
    IF I.D_ID=doctorid THEN
       FLAG:=1;
    END IF;
  END LOOP;
  IF FLAG=1 THEN
    RETURN TRUE;
  ELSE
    RETURN FALSE;
  END IF;
END FIND_DOCTOR_ID;
/

create or replace FUNCTION FIND_NURSE_ID(nurseid IN NURSE.N_ID%TYPE)
RETURN BOOLEAN AS 
 FLAG NUMBER(5):=0;
CURSOR NURSE_REC IS
SELECT N_ID FROM GOVERNS_ROOM;
BEGIN
  FOR I IN NURSE_REC LOOP
    IF I.N_ID=nurseid THEN
       FLAG:=1;
    END IF;
  END LOOP;
  IF FLAG=1 THEN
    RETURN TRUE;
  ELSE
    RETURN FALSE;
  END IF;
END FIND_NURSE_ID;
/

create or replace FUNCTION FIND_PATIENT_ASSIGNED_ROOM(patientid IN ASSIGNED_ROOM.P_ID%TYPE)
RETURN BOOLEAN AS 
FLAG NUMBER(5):=0;
CURSOR P_REC IS
SELECT P_ID FROM ASSIGNED_ROOM ;
BEGIN
  FOR I IN P_REC LOOP
    IF I.P_ID=patientid THEN
       FLAG:=1;
    END IF;
  END LOOP;
  IF FLAG=1 THEN
    RETURN TRUE;
  ELSE
    RETURN FALSE;
  END IF;
END FIND_PATIENT_ASSIGNED_ROOM;
/


create or replace FUNCTION FIND_PATIENT_ASSIST_PATIENT(patientid IN ASSIST_PATIENT.P_ID%TYPE)
RETURN BOOLEAN AS 
FLAG NUMBER(5):=0;
CURSOR P_REC IS
SELECT P_ID FROM ASSIST_PATIENT ;
BEGIN
  FOR I IN P_REC LOOP
    IF I.P_ID=patientid THEN
       FLAG:=1;
    END IF;
  END LOOP;
  IF FLAG=1 THEN
    RETURN TRUE;
  ELSE
    RETURN FALSE;
  END IF;
END FIND_PATIENT_ASSIST_PATIENT;
/


create or replace FUNCTION FIND_PATIENT_ATTEND_PATIENT(patientid IN ATTEND_PATIENT.P_ID%TYPE)
RETURN BOOLEAN AS 
FLAG NUMBER(5):=0;
CURSOR P_REC IS
SELECT P_ID FROM ATTEND_PATIENT ;
BEGIN
  FOR I IN P_REC LOOP
    IF I.P_ID=patientid THEN
       FLAG:=1;
    END IF;
  END LOOP;
  IF FLAG=1 THEN
    RETURN TRUE;
  ELSE
    RETURN FALSE;
  END IF;
END FIND_PATIENT_ATTEND_PATIENT;
/

create or replace FUNCTION FIND_PATIENT_LOG_PATIENT(patientid IN LOG_PATIENT.PATIENT_ID%TYPE)
RETURN BOOLEAN AS 
FLAG NUMBER(5):=0;
CURSOR P_REC IS
SELECT PATIENT_ID FROM LOG_PATIENT ;
BEGIN
  FOR I IN P_REC LOOP
    IF I.PATIENT_ID=patientid THEN
       FLAG:=1;
    END IF;
  END LOOP;
  IF FLAG=1 THEN
    RETURN TRUE;
  ELSE
    RETURN FALSE;
  END IF;
END FIND_PATIENT_LOG_PATIENT;
/

create or replace FUNCTION FIND_RECEPTIONIST_ID(rid in RECEPTIONIST.R_ID%TYPE)
RETURN BOOLEAN AS 
FLAG NUMBER(5):=0;
CURSOR RECEPTIONIST_REC IS
SELECT R_ID FROM ASSIST_PATIENT;
BEGIN
  FOR I IN RECEPTIONIST_REC LOOP
    IF I.R_ID=rid THEN
       FLAG:=1;
    END IF;
  END LOOP;
  IF FLAG=1 THEN
    RETURN TRUE;
  ELSE
    RETURN FALSE;
  END IF;
END FIND_RECEPTIONIST_ID;
/


create or replace FUNCTION FIND_ROOMNO_ASSIGNEDROOM(roomid IN ROOM.ROOM_NO%TYPE)
RETURN BOOLEAN AS 
FLAG NUMBER(5):=0;
CURSOR ROOM_REC IS
SELECT ROOM_NO FROM ASSIGNED_ROOM;
BEGIN
  FOR I IN ROOM_REC LOOP
    IF I.ROOM_NO=roomid THEN
       FLAG:=1;
    END IF;
  END LOOP;
  IF FLAG=1 THEN
    RETURN TRUE;
  ELSE
    RETURN FALSE;
  END IF;
END FIND_ROOMNO_ASSIGNEDROOM;
/


create or replace FUNCTION FIND_ROOMNO_GOVERNSROOM(roomid IN ROOM.ROOM_NO%TYPE)
RETURN BOOLEAN AS 
FLAG NUMBER(5):=0;
CURSOR ROOM_REC IS
SELECT ROOM_NO FROM GOVERNS_ROOM;
BEGIN
  FOR I IN ROOM_REC LOOP
    IF I.ROOM_NO=roomid THEN
       FLAG:=1;
    END IF;
  END LOOP;
  IF FLAG=1 THEN
    RETURN TRUE;
  ELSE
    RETURN FALSE;
  END IF;
END FIND_ROOMNO_GOVERNSROOM;
/



create or replace FUNCTION RECEPTIONIST_EMAIL(uid in RECEPTIONIST.R_EMAIL%TYPE)
RETURN RECEPTIONIST.R_EMAIL%TYPE AS
email RECEPTIONIST.R_EMAIL%TYPE;
BEGIN
  SELECT R_EMAIL INTO email FROM RECEPTIONIST WHERE R_ID=uid;
  RETURN email;
END RECEPTIONIST_EMAIL;
/



create or replace FUNCTION USER_EMAIL(uid in USER_TYPE.U_EMAIL%TYPE)
RETURN USER_TYPE.U_EMAIL%TYPE AS
email USER_TYPE.U_EMAIL%TYPE;
BEGIN
  SELECT U_EMAIL INTO email FROM USER_TYPE WHERE ID=uid;
  RETURN email;
END USER_EMAIL;
/