/*-----------------------------------------------------------------------------------------------------
	FILE: CREATE_PKG.SQL
	DESCRIPTION: THIS SCRIPT CONTAIN PACKAGES
	AUTHOR: SELVA
	DATE CREATED: 13/02/2021
*/-----------------------------------------------------------------------------------------------------


create or replace PACKAGE DELETE_PACKAGE AS 
	   PROCEDURE DELETE_DOCTOR(doctorid in DOCTOR.D_ID%TYPE) ;
	   PROCEDURE DELETE_NURSE(nurseid in NURSE.N_ID%TYPE) ;
	   PROCEDURE DELETE_RECEPTIONIST(recid in RECEPTIONIST.R_ID%TYPE) ;
	   PROCEDURE DELETE_ROOM(roomid in ROOM.ROOM_NO%TYPE) ;
	   PROCEDURE DELETE_PATIENT(patientid IN PATIENT.P_ID%TYPE);
END DELETE_PACKAGE;
/

create or replace PACKAGE BODY DELETE_PACKAGE AS
	  PROCEDURE DELETE_DOCTOR(doctorid in DOCTOR.D_ID%TYPE)  AS
		  BEGIN
			DELETE FROM DOCTOR WHERE D_ID=doctorid;
			IF FIND_DOCTOR_ID(doctorid)=TRUE THEN
				DELETE FROM ATTEND_PATIENT WHERE D_ID=doctorid;
			END IF;
	  END DELETE_DOCTOR;
  
	  PROCEDURE DELETE_NURSE(nurseid in NURSE.N_ID%TYPE)  AS
		  BEGIN
			DELETE FROM NURSE WHERE N_ID=nurseid;
			IF FIND_NURSE_ID(nurseid)=TRUE THEN
				DELETE FROM GOVERNS_ROOM WHERE N_ID=nurseid;
			END IF;
	  END DELETE_NURSE;
	  
	  PROCEDURE DELETE_RECEPTIONIST(recid in RECEPTIONIST.R_ID%TYPE)  AS
		  BEGIN
			DELETE FROM RECEPTIONIST WHERE R_ID=recid;
			DELETE FROM USER_TYPE WHERE ID=recid;
			IF FIND_RECEPTIONIST_ID(recid)=TRUE THEN
				DELETE FROM ASSIST_PATIENT WHERE R_ID=recid;
			END IF;
	  END DELETE_RECEPTIONIST;
	  
	  PROCEDURE DELETE_ROOM(roomid IN ROOM.ROOM_NO%TYPE) AS
	  roomid_assignedroom ROOM.ROOM_NO%TYPE;
	  roomid_governsroom ROOM.ROOM_NO%TYPE;
		  BEGIN
			 DELETE FROM ROOM WHERE ROOM_NO=roomid;
			 IF FIND_ROOMNO_ASSIGNEDROOM(roomid)=TRUE THEN
				 DELETE FROM ASSIGNED_ROOM WHERE ROOM_NO=roomid;
			 END IF;
			 IF FIND_ROOMNO_GOVERNSROOM(roomid)=TRUE THEN
				 DELETE FROM GOVERNS_ROOM WHERE ROOM_NO=roomid;
			 END IF;
	  END DELETE_ROOM;
	  
	  PROCEDURE DELETE_PATIENT(patientid IN PATIENT.P_ID%TYPE) AS
		  BEGIN
			DELETE FROM PATIENT WHERE P_ID=patientid;
			IF FIND_PATIENT_ASSIGNED_ROOM(patientid)=TRUE THEN
			   DELETE FROM ASSIGNED_ROOM WHERE P_ID=patientid;
			END IF;
			IF FIND_PATIENT_ASSIST_PATIENT(patientid)=TRUE THEN
			   DELETE FROM ASSIST_PATIENT WHERE P_ID=patientid;
			END IF;
			IF FIND_PATIENT_ATTEND_PATIENT(patientid)=TRUE THEN
			   DELETE FROM ATTEND_PATIENT WHERE P_ID=patientid;
			END IF;
			IF FIND_PATIENT_LOG_PATIENT(patientid)=TRUE THEN
			   DELETE FROM LOG_PATIENT WHERE PATIENT_ID=patientid;
			END IF;
	  END DELETE_PATIENT;
END DELETE_PACKAGE;
/


create or replace PACKAGE EDIT_PACKAGE AS 
    PROCEDURE EDIT_DOCTOR(id in DOCTOR.D_ID%TYPE,name in DOCTOR.D_NAME%TYPE,address in DOCTOR.D_ADDRESS%TYPE,contact in DOCTOR.D_CONTACT_NO%TYPE,salary in DOCTOR.D_SALARY%TYPE,dob in DOCTOR.D_JOINING_DATE%TYPE,designation in DOCTOR.D_DESIGNATION%TYPE);
    PROCEDURE EDIT_NURSE(id in NURSE.N_ID%TYPE,name in NURSE.N_NAME%TYPE,address in NURSE.N_ADDRESS%TYPE,contact in NURSE.N_CONTACT_NO%TYPE,salary in NURSE.N_SALARY%TYPE,dob in NURSE.N_JOINING_DATE%TYPE,designation in NURSE.N_DESIGNATION%TYPE);    
    PROCEDURE EDIT_RECEPTIONIST(id in RECEPTIONIST.R_ID%TYPE,email in RECEPTIONIST.R_EMAIL%TYPE,name in RECEPTIONIST.R_NAME%TYPE,address in RECEPTIONIST.R_ADDRESS%TYPE,contact in RECEPTIONIST.R_CONTACT_NO%TYPE,salary in RECEPTIONIST.R_SALARY%TYPE,dob in RECEPTIONIST.R_JOINING_DATE%TYPE,designation in RECEPTIONIST.R_DESIGNATION%TYPE);    
    PROCEDURE EDIT_ROOM(roomid in ROOM.ROOM_NO%TYPE,roomtype in ROOM.ROOM_TYPE%TYPE,roomcost IN ROOM.ROOM_COST%TYPE);
    PROCEDURE EDIT_PATIENT(id in PATIENT.P_ID%TYPE,name in PATIENT.P_NAME%TYPE,contact in PATIENT.P_CONTACT_NO%TYPE,address in PATIENT.P_ADDRESS%TYPE,gender in PATIENT.P_GENDER%TYPE,dob IN PATIENT.P_DOB%TYPE);
END EDIT_PACKAGE;
/

create or replace PACKAGE BODY EDIT_PACKAGE AS
	  PROCEDURE EDIT_DOCTOR(id in DOCTOR.D_ID%TYPE,name in DOCTOR.D_NAME%TYPE,address in DOCTOR.D_ADDRESS%TYPE,contact in DOCTOR.D_CONTACT_NO%TYPE,salary in DOCTOR.D_SALARY%TYPE,dob in DOCTOR.D_JOINING_DATE%TYPE,designation in DOCTOR.D_DESIGNATION%TYPE) AS
		  BEGIN
			UPDATE DOCTOR SET D_NAME=name, D_ADDRESS=address, D_CONTACT_NO=contact,D_SALARY=salary,D_JOINING_DATE=DOB,D_DESIGNATION=designation WHERE D_ID=id;
		  END EDIT_DOCTOR;

	  PROCEDURE EDIT_NURSE(id in NURSE.N_ID%TYPE,name in NURSE.N_NAME%TYPE,address in NURSE.N_ADDRESS%TYPE,contact in NURSE.N_CONTACT_NO%TYPE,salary in NURSE.N_SALARY%TYPE,dob in NURSE.N_JOINING_DATE%TYPE,designation in NURSE.N_DESIGNATION%TYPE) AS
		  BEGIN
			UPDATE NURSE SET N_NAME=name, N_ADDRESS=address, N_CONTACT_NO=contact,N_SALARY=salary,N_JOINING_DATE=DOB,N_DESIGNATION=designation WHERE N_ID=id; 
		  END EDIT_NURSE;
	  
	  PROCEDURE EDIT_RECEPTIONIST(id in RECEPTIONIST.R_ID%TYPE,email in RECEPTIONIST.R_EMAIL%TYPE,name in RECEPTIONIST.R_NAME%TYPE,address in RECEPTIONIST.R_ADDRESS%TYPE,contact in RECEPTIONIST.R_CONTACT_NO%TYPE,salary in RECEPTIONIST.R_SALARY%TYPE,dob in RECEPTIONIST.R_JOINING_DATE%TYPE,designation in RECEPTIONIST.R_DESIGNATION%TYPE) AS    
	  oldemail RECEPTIONIST.R_EMAIL%TYPE;
	  newemail RECEPTIONIST.R_EMAIL%TYPE;
	  userid USER_TYPE.ID%TYPE:=id;
		  BEGIN
			oldemail:=RECEPTIONIST_EMAIL(id);
			UPDATE RECEPTIONIST SET R_NAME=name,R_EMAIL=email, R_ADDRESS=address, R_CONTACT_NO=contact,R_SALARY=salary,R_JOINING_DATE=DOB,R_DESIGNATION=designation WHERE R_ID=id; 
			newemail:=RECEPTIONIST_EMAIL(id);
			IF oldemail!=newemail THEN
			   UPDATE USER_TYPE SET U_EMAIL=newemail WHERE ID=userid;
			END IF;
	  END EDIT_RECEPTIONIST;
	  
	  PROCEDURE EDIT_ROOM(roomid in ROOM.ROOM_NO%TYPE,roomtype in ROOM.ROOM_TYPE%TYPE,roomcost IN ROOM.ROOM_COST%TYPE) AS
		  BEGIN
			UPDATE ROOM SET ROOM_TYPE=roomtype,ROOM_COST=roomcost WHERE ROOM_NO=roomid;
		  END EDIT_ROOM;

	PROCEDURE EDIT_PATIENT(id in PATIENT.P_ID%TYPE,name in PATIENT.P_NAME%TYPE,contact in PATIENT.P_CONTACT_NO%TYPE,address in PATIENT.P_ADDRESS%TYPE,gender in PATIENT.P_GENDER%TYPE,dob IN PATIENT.P_DOB%TYPE) AS
		  BEGIN
			UPDATE PATIENT SET P_NAME=name,P_CONTACT_NO=contact,P_ADDRESS=address,P_GENDER=gender,P_DOB=dob where P_ID=id;
		  END EDIT_PATIENT;
		  
END EDIT_PACKAGE; 
/