/*-----------------------------------------------------------------------------------------------------
	FILE: CREATE_TABLES.SQL
	DESCRIPTION: THIS SCRIPT CONTAIN TABLE CREATION QURIES
	AUTHOR: SELVA
	DATE CREATED: 03/02/2021
*/-----------------------------------------------------------------------------------------------------

-- create the tables

CREATE TABLE ADMIN
(ADMIN_ID NUMBER (7) PRIMARY KEY,
ADMIN_NAME VARCHAR2(50) NOT NULL,
ADMIN_ADDRESS VARCHAR2(100) NULL,
ADMIN_CONTACT_NO NUMBER(11) NULL,
ADMIN_EMAIL VARCHAR2(200) NULL,
DATE_OF_BIRTH DATE NULL);


CREATE TABLE PATIENT
(P_ID NUMBER(7) PRIMARY KEY,
P_NAME VARCHAR2(50) NOT NULL,
P_ADDRESS VARCHAR2(100) NOT NULL,
P_GENDER VARCHAR2(10) NOT NULL,
P_DOB DATE NOT NULL,
P_CONTACT_NO NUMBER(11) NOT NULL,
P_STATUS VARCHAR2(30) NOT NULL,
P_CONDITION VARCHAR2(30));


CREATE TABLE ROOM
(ROOM_NO NUMBER(7) PRIMARY KEY,
ROOM_TYPE VARCHAR2(20) NOT NULL,
ROOM_COST NUMBER(5) NOT NULL,
ROOM_STATUS VARCHAR2(20) NOT NULL);


CREATE TABLE DOCTOR
(D_ID NUMBER(7) PRIMARY KEY,
D_NAME VARCHAR2(50) NOT NULL,
D_ADDRESS VARCHAR2(50) NOT NULL,
D_CONTACT_NO NUMBER(11) NOT NULL,
D_JOINING_DATE DATE NOT NULL,
D_SALARY NUMBER(10) NOT NULL,
D_DESIGNATION VARCHAR2(50) NOT NULL);


CREATE TABLE NURSE
(N_ID NUMBER (7) PRIMARY KEY,
N_NAME VARCHAR2(50) NOT NULL,
N_ADDRESS VARCHAR2(50) NOT NULL,
N_CONTACT_NO NUMBER(11) NOT NULL,
N_JOINING_DATE DATE NOT NULL,
N_SALARY NUMBER(10) NOT NULL,
N_DESIGNATION VARCHAR2(50) NOT NULL);


CREATE TABLE RECEPTIONIST
(R_ID NUMBER (7) PRIMARY KEY,
R_NAME VARCHAR2(50) NOT NULL,
R_EMAIL VARCHAR2(50) NOT NULL,
R_ADDRESS VARCHAR2(50) NOT NULL,
R_CONTACT_NO NUMBER(11) NOT NULL,
R_JOINING_DATE DATE NOT NULL,
R_SALARY NUMBER(10) NOT NULL,
R_DESIGNATION VARCHAR2(50) NOT NULL);


CREATE TABLE USER_TYPE
(U_ID NUMBER (7) PRIMARY KEY,
ID NUMBER (7) NOT NULL,
U_TYPE VARCHAR2(50) NOT NULL,
U_EMAIL VARCHAR2(50) NOT NULL,
U_PASSWORD VARCHAR2(50) NOT NULL);


CREATE TABLE ASSIGNED_ROOM
(AR_ID NUMBER (7) PRIMARY KEY,
P_ID NUMBER (7) NOT NULL,
ROOM_NO NUMBER(7) NOT NULL);


CREATE TABLE ASSIST_PATIENT
(AP_ID NUMBER (7) PRIMARY KEY,
P_ID NUMBER (7) NOT NULL,
R_ID NUMBER (7) NOT NULL);


CREATE TABLE GOVERNS_ROOM
(GR_ID NUMBER (7) PRIMARY KEY,
N_ID NUMBER (7) NOT NULL,
ROOM_NO NUMBER(7) NOT NULL);


CREATE TABLE ATTEND_PATIENT
(ATP_ID NUMBER (7) PRIMARY KEY,
P_ID NUMBER (7) NOT NULL,
D_ID NUMBER (7) NOT NULL);


CREATE TABLE LOG_PATIENT
   (	"PATIENT_ID" NUMBER NOT NULL ENABLE,
	"RELEASE_DATE" DATE NULL, 
	"ADMIT_DATE" DATE NULL, 
	 CONSTRAINT "LOG_PATIENT_PK" PRIMARY KEY ("PATIENT_ID") ENABLE
   );


CREATE TABLE LOGIN_INFO 
   	("LID" NUMBER(20,0) NOT NULL ENABLE, 
	"LOGGED_PERSON" NUMBER(20,0), 
	"LOGIN_DATE" DATE,
	 CONSTRAINT "LOGIN_INFO_PK" PRIMARY KEY ("LID") );


CREATE TABLE ERROR_LOG
(
ERRCODE	VARCHAR2(10),
ERRMSG  VARCHAR(30),
USRNME  VARCHAR2(10),
ERRTIME TIMESTAMP,
BLOCKNAME VARCHAR2(30)
);

